### ISSUE TITLE
Abnormal termination in ion-rs 0.15 when using `element_reader`

### ISSUE THREAD

**Issue by jpschorr** [amazon-ion/ion-rust#461]
When attempting to upgrade from `0.14` to `0.15`, I found several ion text files that parse correctly (using `element_reader`) with `ion-rs = "0.14"`, but die with `signal: 11, SIGSEGV: invalid memory reference` (on ubuntu) or `signal: 4, SIGILL: illegal instruction` (on mac) using `ion-rs = "0.15"`

Partiql-lang-rust PR with the upgrade: https://github.com/partiql/partiql-lang-rust/pull/280
Failed build: https://github.com/partiql/partiql-lang-rust/actions/runs/3972514590/jobs/6810485755

---

partiql-test files that seem to display the above failure states:
- https://github.com/partiql/partiql-tests/blob/main/partiql-tests-data/eval/primitives/naughty-strings.ion
- https://github.com/partiql/partiql-tests/blob/main/partiql-tests-data/eval/primitives/functions/trim.ion
- https://github.com/partiql/partiql-tests/blob/main/partiql-tests-data/eval/primitives/functions/char_length.ion

---
Self-contained  example of the failure (apologies for the length of the `trim.ion` file, reducing it any more seems to make the bug no longer exhibit):

Cargo.toml:

```
[package]
name = "ion_test"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
ion-rs = "0.14"
```

src/lib.rs:
```
#[cfg(test)]
mod tests {
    use ion_rs::value::reader::{element_reader, ElementReader};
    static ION_DATA: &'static [u8] = include_bytes!("trim.ion");

    #[test]
    fn ion_test() {
        element_reader().read_all(ION_DATA).unwrap();
    }
}
```

src/trim.ion:
```
trim::[
  {
    name:"trim valid cases{spec:\"both\",to_remove:\"12\",target:\"111112a1212121211\",result:\"a\"}",
    statement:"trim(both '12' from '111112a1212121211')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"a"
    }
  },
  {
    name:"trim valid cases{spec:\"leading\",to_remove:\"12\",target:\"111112a1212121211\",result:\"a1212121211\"}",
    statement:"trim(leading '12' from '111112a1212121211')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"a1212121211"
    }
  },
  {
    name:"trim valid cases{spec:\"trailing\",to_remove:\"12\",target:\"111112a1212121211\",result:\"111112a\"}",
    statement:"trim(trailing '12' from '111112a1212121211')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"111112a"
    }
  },
  {
    name:"trim valid cases{spec:\"both\",to_remove:\"\\U0001f4a9\\U0001f638\",target:\"\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638a\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638\",result:\"1\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638a\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\"}",
    statement:"trim(both '💩😸' from '💩💩💩😸😸😸1💩💩💩😸😸😸a💩💩💩😸😸😸1💩💩💩😸😸😸')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"1💩💩💩😸😸😸a💩💩💩😸😸😸1"
    }
  },
  {
    name:"trim valid cases{spec:\"leading\",to_remove:\"\\U0001f4a9\\U0001f638\",target:\"\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638a\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638\",result:\"1\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638a\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638\"}",
    statement:"trim(leading '💩😸' from '💩💩💩😸😸😸1💩💩💩😸😸😸a💩💩💩😸😸😸1💩💩💩😸😸😸')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"1💩💩💩😸😸😸a💩💩💩😸😸😸1💩💩💩😸😸😸"
    }
  },
  {
    name:"trim valid cases{spec:\"trailing\",to_remove:\"\\U0001f4a9\\U0001f638\",target:\"\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638a\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638\",result:\"\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f638a\\U0001f4a9\\U0001f4a9\\U0001f4a9\\U0001f638\\U0001f638\\U0001f6381\"}",
    statement:"trim(trailing '💩😸' from '💩💩💩😸😸😸1💩💩💩😸😸😸a💩💩💩😸😸😸1💩💩💩😸😸😸')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"💩💩💩😸😸😸1💩💩💩😸😸😸a💩💩💩😸😸😸1"
    }
  },
  {
    name:"trim valid cases{spec:\"both\",to_remove:\"\\u8a71 \",target:\"\\u8a71\\u8a71 \\u8a71\\u8a71\\u8a71\\u8a71\\u8a71\\u8a71\\u8cbb\\u8c37\\u6599\\u6751\\u80fd\\u8a71\\u8a71\\u8a71\\u8a71 \\u8a71\\u8a71\\u8a71\\u8a71    \",result:\"\\u8cbb\\u8c37\\u6599\\u6751\\u80fd\"}",
    statement:"trim(both '話 ' from '話話 話話話話話話費谷料村能話話話話 話話話話 ')",
    assert:{
      result:EvaluationSuccess,
      evalMode:[
        EvalModeCoerce,
        EvalModeError
      ],
      output:"費谷料村能"
    }
  },
]
```

**Comment by nirosys** [comment]
Using the provided minimal repro (thank you!) I get a SIGTRAP on OSX (12.4, M1, Debug build). If I run with a release build, I get:
```
thread 'tests::ion_test' panicked at 'called `Result::unwrap()` on an `Err` value: DecodingError { description: "Parsing error occurred while parsing a struct field value near line 75:\n'\"trim(both '話 ' from '話話 話話話話話話費谷料村�'\nunrecognized input near line 75: strings cannot contain unescaped control characters: '\"trim(both '話 ' from '
話話 話話話話話話費谷料村�'" }', src/lib.rs:8:45
```
Looking at the debug build:
```
(lldb) bt                                                                                                                                                                       
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0                                                                                    
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0                                                                                    
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0                                                                                    
* thread #2, name = 'tests::ion_test', stop reason = EXC_BREAKPOINT (code=1, subcode=0x100108588)                                                                               
  * frame #0: 0x0000000100108588 ion_rust_test-2b15050c0784e0a6`core::hint::unreachable_unchecked::h8c9a9e35a01d8f47 at hint.rs:104:9                                           
    frame #1: 0x0000000100105998 ion_rust_test-2b15050c0784e0a6`core::option::Option$LT$T$GT$::unwrap_unchecked::h393118bda4c68756(self=Option<&u8> @ 0x000000016fffd940) at opt
ion.rs:893:30                                                                                                                                                                   
    frame #2: 0x00000001001056d4 ion_rust_test-2b15050c0784e0a6`core::str::validations::next_code_point::h1fbc0471fe6b13a6(bytes=0x000000016fffdc68) at validations.rs:56:27    
    frame #3: 0x000000010004e128 ion_rust_test-2b15050c0784e0a6`_$LT$core..str..iter..CharIndices$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::heab6784930c8c53c
 [inlined] _$LT$core..str..iter..Chars$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::ha53ab73a0914c100 at iter.rs:44:18                                          
    frame #4: 0x000000010004e124 ion_rust_test-2b15050c0784e0a6`_$LT$core..str..iter..CharIndices$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::heab6784930c8c53c
(self=0x000000016fffdc60) at iter.rs:140:15                                                                                                                                     
    frame #5: 0x0000000100059dd0 ion_rust_test-2b15050c0784e0a6`ion_rs::text::parsers::string::short_string_fragment_without_escaped_text::h257d30f8021dbb00(input=(data_ptr = "
trim(both '話 ' from '話話 話話話話話話費谷料村能話\xe8\xa9", length = 62)) at string.rs:136:36                                                                                 
    frame #6: 0x00000001000ae5a0 ion_rust_test-2b15050c0784e0a6`core::ops::function::FnMut::call_mut::hc32e415356dd1f11((null)=0x000000016fffe20f, (null)=(&str) @ 0x000000016ff
fdd18) at function.rs:166:5                                                                                                                                                     
    frame #7: 0x0000000100045fa4 ion_rust_test-2b15050c0784e0a6`_$LT$F$u20$as$u20$nom..internal..Parser$LT$I$C$O$C$E$GT$$GT$::parse::h2f17191d02601b87(self=0x000000016fffe20f, 
i=(data_ptr = "trim(both '話 ' from '話話 話話話話話話費谷料村能話\xe8\xa9", length = 62)) at internal.rs:325:5                                                                 
    frame #8: 0x00000001000dc034 ion_rust_test-2b15050c0784e0a6`_$LT$$LP$A$C$B$C$C$RP$$u20$as$u20$nom..branch..Alt$LT$Input$C$Output$C$Error$GT$$GT$::choice::hc76538537afb0ef8(
self=0x000000016fffe20f, input=(data_ptr = "trim(both '話 ' from '話話 話話話話話話費谷料村能話\xe8\xa9", length = 62)) at mod.rs:136:33                                        
    frame #9: 0x000000010006bac0 ion_rust_test-2b15050c0784e0a6`nom::branch::alt::_$u7b$$u7b$closure$u7d$$u7d$::h901e936a0982c03a(i=(data_ptr = "trim(both '話 ' from '話話 話話
話話話話費谷料村能話\xe8\xa9", length = 62)) at mod.rs:50:15                                                                                                                    
    frame #10: 0x0000000100059d54 ion_rust_test-2b15050c0784e0a6`ion_rs::text::parsers::string::short_string_fragment::h276696cc670e77e2(input=(data_ptr = "trim(both '話 ' from
 '話話 話話話話話話費谷料村能話\xe8\xa9", length = 62)) at string.rs:125:5                                                                                                      
    frame #11: 0x00000001000ad690 ion_rust_test-2b15050c0784e0a6`core::ops::function::FnMut::call_mut::h32a8cb11b1fdf179((null)=0x000000016fffe5bf, (null)=(&str) @ 0x000000016f
ffe248) at function.rs:166:5       
```
PoI:
```
    frame #5: 0x0000000100059dd0 ion_rust_test-2b15050c0784e0a6`ion_rs::text::parsers::string::short_string_fragment_without_escaped_text::h257d30f8021dbb00(input=(data_ptr = "
trim(both '話 ' from '話話 話話話話話話費谷料村能話\xe8\xa9", length = 62)) at string.rs:136:36   
```

```
(lldb) f 5
frame #5: 0x0000000100059dd0 ion_rust_test-2b15050c0784e0a6`ion_rs::text::parsers::string::short_string_fragment_without_escaped_text::h257d30f8021dbb00(input=(data_ptr = "trim(both '話 ' from '話話 話話話話話話費谷料村能話\xe8\xa9", length = 62)) at string.rs:136:36
   133  pub(in crate::text::parsers) fn short_string_fragment_without_escaped_text(
   134      input: &str,
   135  ) -> IonParseResult<StringFragment> {
-> 136      for (byte_index, character) in input.char_indices() {
   137          match character {
   138              '\\' | '\r' | '\"' => {
   139                  // Escapes and carriage returns are handled by other clob fragment parsers, while
(lldb)
```

Looking at the ion file:
```
glitch@logic ~/C/ion-rust-test> hexdump -C src/trim.ion | fgrep -A5 -B1 "trim(both '話"
00000fb0  0a 20 20 20 20 73 74 61  74 65 6d 65 6e 74 3a 22  |.    statement:"|
00000fc0  74 72 69 6d 28 62 6f 74  68 20 27 e8 a9 b1 20 27  |trim(both '話 '|
00000fd0  20 66 72 6f 6d 20 27 e8  a9 b1 e8 a9 b1 20 e8 a9  | from '話話 |
00000fe0  b1 e8 a9 b1 e8 a9 b1 e8  a9 b1 e8 a9 b1 e8 a9 b1  |話話話話話|
00000ff0  e8 b2 bb e8 b0 b7 e6 96  99 e6 9d 91 e8 83 bd e8  |費谷.....|
00001000  a9 b1 e8 a9 b1 e8 a9 b1  e8 a9 b1 20 e8 a9 b1 e8  |話話話 話|
00001010  a9 b1 e8 a9 b1 e8 a9 b1  20 27 29 22 2c 0a 20 20  |話話 ')",.  |
```

0xfc0 = 4032, plus the 62 bytes from the string puts the end of the string at around 4064, which is reeeeaaal close to the initial buffer size. Could be a boundary issue with the non-blocking reader, which was added in 0.15. That string is definitely truncated mid unicode sequence.

Odd that the debug build SIGTRAPs, while the release build correctly panics, at least on this machine.

I can jump on this ASAP. Thank you again for the awesome minimal repro!

**Comment by nirosys** [comment]
Just merged ea053f934 which should address this issue.

**Comment by nirosys** [comment]
Leaving this issue open for a little longer until I add a unit test for regression testing. Fix has been merged and should be in the next release.

**Comment by nirosys** [comment]
Closing this since the fix has been released with 0.16; PR included a test for regression.
